// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA9jqpPjHmwnHGrkt_dytcA7zGf-VlzQ6Y',
    appId: '1:1013785458479:android:0153dd243cd1b1bcf993da',
    messagingSenderId: '1013785458479',
    projectId: 'calendar-scheduler-fb4a0',
    storageBucket: 'calendar-scheduler-fb4a0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDEdCj1uYKOLNpC6eCQ64GHRLyJVn39PSE',
    appId: '1:1013785458479:ios:436fd87f6960f979f993da',
    messagingSenderId: '1013785458479',
    projectId: 'calendar-scheduler-fb4a0',
    storageBucket: 'calendar-scheduler-fb4a0.appspot.com',
    androidClientId: '1013785458479-1bongvbtf7lpv0pu4cs5h5takb3mn2qt.apps.googleusercontent.com',
    iosClientId: '1013785458479-hecrh8u0e8r6ujh0v1cjsan20gdh67rd.apps.googleusercontent.com',
    iosBundleId: 'com.example.calendarScheduler',
  );
}
